export interface RegionInfo {
  slug: string;
  name: string;
}

export const REGION_MAPPING: Record<string, RegionInfo> = {
  '01': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '03': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '07': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '15': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '26': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '38': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '42': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '43': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '63': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '69': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '73': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },
  '74': { slug: 'auvergne-rhone-alpes', name: 'Auvergne-Rhône-Alpes' },

  '21': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '25': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '39': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '58': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '70': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '71': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '89': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },
  '90': { slug: 'bourgogne-franche-comte', name: 'Bourgogne-Franche-Comté' },

  '22': { slug: 'bretagne', name: 'Bretagne' },
  '29': { slug: 'bretagne', name: 'Bretagne' },
  '35': { slug: 'bretagne', name: 'Bretagne' },
  '56': { slug: 'bretagne', name: 'Bretagne' },

  '18': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },
  '28': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },
  '36': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },
  '37': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },
  '41': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },
  '45': { slug: 'centre-val-de-loire', name: 'Centre-Val de Loire' },

  '2A': { slug: 'corse', name: 'Corse' },
  '2B': { slug: 'corse', name: 'Corse' },

  '08': { slug: 'grand-est', name: 'Grand Est' },
  '10': { slug: 'grand-est', name: 'Grand Est' },
  '51': { slug: 'grand-est', name: 'Grand Est' },
  '52': { slug: 'grand-est', name: 'Grand Est' },
  '54': { slug: 'grand-est', name: 'Grand Est' },
  '55': { slug: 'grand-est', name: 'Grand Est' },
  '57': { slug: 'grand-est', name: 'Grand Est' },
  '67': { slug: 'grand-est', name: 'Grand Est' },
  '68': { slug: 'grand-est', name: 'Grand Est' },
  '88': { slug: 'grand-est', name: 'Grand Est' },

  '02': { slug: 'hauts-de-france', name: 'Hauts-de-France' },
  '59': { slug: 'hauts-de-france', name: 'Hauts-de-France' },
  '60': { slug: 'hauts-de-france', name: 'Hauts-de-France' },
  '62': { slug: 'hauts-de-france', name: 'Hauts-de-France' },
  '80': { slug: 'hauts-de-france', name: 'Hauts-de-France' },

  '75': { slug: 'ile-de-france', name: 'Île-de-France' },
  '77': { slug: 'ile-de-france', name: 'Île-de-France' },
  '78': { slug: 'ile-de-france', name: 'Île-de-France' },
  '91': { slug: 'ile-de-france', name: 'Île-de-France' },
  '92': { slug: 'ile-de-france', name: 'Île-de-France' },
  '93': { slug: 'ile-de-france', name: 'Île-de-France' },
  '94': { slug: 'ile-de-france', name: 'Île-de-France' },
  '95': { slug: 'ile-de-france', name: 'Île-de-France' },

  '14': { slug: 'normandie', name: 'Normandie' },
  '27': { slug: 'normandie', name: 'Normandie' },
  '50': { slug: 'normandie', name: 'Normandie' },
  '61': { slug: 'normandie', name: 'Normandie' },
  '76': { slug: 'normandie', name: 'Normandie' },

  '16': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '17': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '19': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '23': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '24': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '33': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '40': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '47': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '64': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '79': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '86': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },
  '87': { slug: 'nouvelle-aquitaine', name: 'Nouvelle-Aquitaine' },

  '09': { slug: 'occitanie', name: 'Occitanie' },
  '11': { slug: 'occitanie', name: 'Occitanie' },
  '12': { slug: 'occitanie', name: 'Occitanie' },
  '30': { slug: 'occitanie', name: 'Occitanie' },
  '31': { slug: 'occitanie', name: 'Occitanie' },
  '32': { slug: 'occitanie', name: 'Occitanie' },
  '34': { slug: 'occitanie', name: 'Occitanie' },
  '46': { slug: 'occitanie', name: 'Occitanie' },
  '48': { slug: 'occitanie', name: 'Occitanie' },
  '65': { slug: 'occitanie', name: 'Occitanie' },
  '66': { slug: 'occitanie', name: 'Occitanie' },
  '81': { slug: 'occitanie', name: 'Occitanie' },
  '82': { slug: 'occitanie', name: 'Occitanie' },

  '44': { slug: 'pays-de-la-loire', name: 'Pays de la Loire' },
  '49': { slug: 'pays-de-la-loire', name: 'Pays de la Loire' },
  '53': { slug: 'pays-de-la-loire', name: 'Pays de la Loire' },
  '72': { slug: 'pays-de-la-loire', name: 'Pays de la Loire' },
  '85': { slug: 'pays-de-la-loire', name: 'Pays de la Loire' },

  '04': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },
  '05': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },
  '06': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },
  '13': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },
  '83': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },
  '84': { slug: 'provence-alpes-cote-d-azur', name: "Provence-Alpes-Côte d'Azur" },

  '971': { slug: 'guadeloupe', name: 'Guadeloupe' },
  '972': { slug: 'martinique', name: 'Martinique' },
  '973': { slug: 'guyane', name: 'Guyane' },
  '974': { slug: 'la-reunion', name: 'La Réunion' },
  '976': { slug: 'mayotte', name: 'Mayotte' },
};

export const DEPARTMENT_NAMES: Record<string, string> = {
  '01': 'Ain', '02': 'Aisne', '03': 'Allier', '04': 'Alpes-de-Haute-Provence',
  '05': 'Hautes-Alpes', '06': 'Alpes-Maritimes', '07': 'Ardèche', '08': 'Ardennes',
  '09': 'Ariège', '10': 'Aube', '11': 'Aude', '12': 'Aveyron',
  '13': 'Bouches-du-Rhône', '14': 'Calvados', '15': 'Cantal', '16': 'Charente',
  '17': 'Charente-Maritime', '18': 'Cher', '19': 'Corrèze',
  '2A': 'Corse-du-Sud', '2B': 'Haute-Corse',
  '21': "Côte-d'Or", '22': "Côtes-d'Armor", '23': 'Creuse', '24': 'Dordogne',
  '25': 'Doubs', '26': 'Drôme', '27': 'Eure', '28': 'Eure-et-Loir',
  '29': 'Finistère', '30': 'Gard', '31': 'Haute-Garonne', '32': 'Gers',
  '33': 'Gironde', '34': 'Hérault', '35': 'Ille-et-Vilaine', '36': 'Indre',
  '37': 'Indre-et-Loire', '38': 'Isère', '39': 'Jura', '40': 'Landes',
  '41': 'Loir-et-Cher', '42': 'Loire', '43': 'Haute-Loire', '44': 'Loire-Atlantique',
  '45': 'Loiret', '46': 'Lot', '47': 'Lot-et-Garonne', '48': 'Lozère',
  '49': 'Maine-et-Loire', '50': 'Manche', '51': 'Marne', '52': 'Haute-Marne',
  '53': 'Mayenne', '54': 'Meurthe-et-Moselle', '55': 'Meuse', '56': 'Morbihan',
  '57': 'Moselle', '58': 'Nièvre', '59': 'Nord', '60': 'Oise',
  '61': 'Orne', '62': 'Pas-de-Calais', '63': 'Puy-de-Dôme', '64': 'Pyrénées-Atlantiques',
  '65': 'Hautes-Pyrénées', '66': 'Pyrénées-Orientales', '67': 'Bas-Rhin', '68': 'Haut-Rhin',
  '69': 'Rhône', '70': 'Haute-Saône', '71': 'Saône-et-Loire', '72': 'Sarthe',
  '73': 'Savoie', '74': 'Haute-Savoie', '75': 'Paris', '76': 'Seine-Maritime',
  '77': 'Seine-et-Marne', '78': 'Yvelines', '79': 'Deux-Sèvres', '80': 'Somme',
  '81': 'Tarn', '82': 'Tarn-et-Garonne', '83': 'Var', '84': 'Vaucluse',
  '85': 'Vendée', '86': 'Vienne', '87': 'Haute-Vienne', '88': 'Vosges',
  '89': 'Yonne', '90': 'Territoire de Belfort', '91': 'Essonne',
  '92': 'Hauts-de-Seine', '93': 'Seine-Saint-Denis', '94': 'Val-de-Marne',
  '95': "Val-d'Oise", '971': 'Guadeloupe', '972': 'Martinique',
  '973': 'Guyane', '974': 'La Réunion', '976': 'Mayotte',
};
